### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 3JoB** [3JoB/telebot#28]
TEP is a fork of https://gopkg.in/telebot.v3. TEP can follow BotAPI updates faster, as well as some more radical optimizations (of course, there may be wrong modifications, and it is not necessarily stable. , because I often forget to test and I don't like unit tests).

Now I will push the latest roadmap here, and it will be continuously updated. If you have any nice features, please try merging them into telebot first instead of TEP. Only if your merge is rejected by telebot or there is no response for a long time, you should send a merge request to TEP.

By the way, some methods of telebot and TEP are different, please do not copy and paste directly.

****

## Tasks
- [x] Upgrade the network framework to resty-ilo to coexist with fasthttp
- [x] PoolingContext
- [x] Modify Raw value passing to avoid more copies.
- [x] Remove or avoid regular expressions.
- [x] Optimize the way errors exist.
- [x] The middleware uses a method like Next() to continue.

**Comment by 3JoB** [comment]
Version 2 is currently under stable development, and I will rewrite the documentation when it is almost ready.
